03_django/CRUD_Template/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [    
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # NEW(GET)  + CREATE(POST)
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'), #EDIT(GET) + UPDATE(POST)
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'), # DETAIL(GET) + CREATE(POST)
    path('<int:article_pk>/<int:comment_pk>/comments_delete/', views.comment_delete, name='comment_delete'),

]

03_django/CRUD_Template/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jobs/', include('jobs.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_django/CRUD_Template/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

03_django/CRUD_Template/articles/models.py
from django.urls import reverse
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    #객체 표현
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return f'/articles/{ self.pk }/'
        # return reverse('articles:detail', args=[self.pk]) # articles/10/
        return reverse('articles:detail', kwargs={'article_pk': self.pk}) # articles/10/
        # 주의사항
        # reverse 함수에 args 랑 kwargs를 동시에 인자로 보낼 수 없다.

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        # return self.content
        return f'<Article({self.article_id}) : Comment({self.pk})-{self.content}'

03_django/CRUD_Template/jobs/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Jobs(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("jobs:detail", kwargs={"pk": self.pk})

03_django/CRUD_Template/articles/views.py
from IPython import embed
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from .models import Article, Comment


# Create your views here.

def index(request):
    # articles = Article.objects.all()
    articles = Article.objects.order_by('-pk') #DB가 변경
    # articles = Article.objects.all()[::-1] #python이 변경
    context = {'articles':articles}
    return render(request, 'articles/index.html', context)

def create(request):
    #CREATE
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article(title=title, content=content)
        article.save()
        return redirect(article) #메인 페이지
    #NEW
    else:
        return render(request, 'articles/create.html')

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # article.get_absolute_url()
    comments = article.comment_set.all()
    context ={'article': article, 'comments': comments}
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        redirect(article)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect(article)
    else:
        context = {'article': article}
        return render(request, 'articles/update.html', context)

def comments_create(request, article_pk):
    # 댓글을 달 게시글
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        #form 에서 넘어온 댓글 정보
        content = request.POST.get('content')
        # 댓글 생성 및 저장
        comment = Comment(article=article, content=content,)
        comment.save()
        return redirect(article)
        # return redirect('articles:detail', article.pk)
        # return redirect('articles:detail', article_pk)
    else:
        return redirect(article)

def comment_delete(request, article_pk,comment_pk):
    comment = Comment.objects.get(id=comment_pk)
    # article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('articles:detail', article_pk)
        # return redirect(article)
    else:
        return redirect('articles:detail', article_pk)
        # return redirect(article)

03_django/CRUD_Template/jobs/views.py
import requests
from pprint import pprint
from faker import Faker
from decouple import config
from django.shortcuts import render
from .models import Jobs 




# Create your views here.
def index(request):
    # if request.method == 'POST':
    #     name=request.POST.get('name')
        
    #     past_job = Faker('ko_KR').job()
    #     jobs = Jobs(name=name, past_job=past_job)
    #     jobs.save()
    #     context = {'jobs':jobs}
    #     return render(request, 'jobs/result.html', context)
    # else:
    return render(request, 'jobs/index.html')


def past_life(request):
    #사용자로부터 이름
    name = request.POST.get('name')

    #db에 매칭되는 name 가져오기
    #Jobs.objects.get(name=name)
    #get이 간단하지만 해당 값이 없을 경우 에러가 발생한다.
    #filter : 한개던 0개던 상관없이 무조건 쿼리셋으로 가져옴
    # filter는 한개던 0개던 상관없이 가져옴
    person = Jobs.objects.filter(name=name).first()

    #db에 person이 있는지 없는지 판단
    if person:
        past_job = person.past_job
    else: #db에 기존 이름이 없다면(즉 person이 빈 쿼리셋)
        faker = Faker()
        past_job = faker.job()
        person = Jobs(name=name, past_job=past_job) #새로운 레코드를 추가한다.
        person.save()

    #GIPHY (past_job 을 API 에 요청을 보내서 응답을 받음)
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1'
    data = requests.get(url).json()
    try:
      image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None

    context = {'person':person, 'image':image,}
    return render(request, 'jobs/past_life.html', context)

03_django/CRUD_Template/articles/templates/articles/create.html
{% extends "base.html" %}


{% block content %}
  <h1 class="text-center">UPDATE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="제출"> 
  </form>


{% endblock  %}

03_django/CRUD_Template/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">DETALIL</h1>
<h2>{{ article.pk }} 번째 글</h2>
<hr>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성 시각 : {{ article.created_at }}</p>
<p>수정 시각 : {{ article.update_at }}</p>
<hr>
<!-- 댓글 작성 form -->
<form action="{% url 'articles:comments_create' article.pk %}" method="POST">
  {% csrf_token %}
  <label for="content">CONTENT</label>
  <input type="text" name="content" id="content">
  <input type="submit" value="submit">
</form>
<hr>
<p><b>{{ comments|length }} 개의 댓글</b></p>
<hr>
{% for comment in comments %}
  <p> 내용 : {{ comment.content }} </p>
  <p>생성날짜 : {{ comment.created_at }} </p>
  <p style="display:inline;">수정 날짜 : {{ article.update_at }}</p>
  <form action="{% url 'articles:comment_delete' article.pk comment.pk%}" method="POST" onclick="return confirm('댓글 삭제?')" style="display:inline;">
  {% csrf_token %}
  <input type="submit" value="DELETE">
</form>
<hr>
{% empty %}
  <p><b>댓글이 없어요..</b></p>
<hr>
  
{% endfor %}


<a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
<a href="{% url 'articles:index' %}">[BACK]</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울거야?')">
  {% csrf_token %}
  <input type="submit" value="DELETE">
</form>


{% endblock  %}

03_django/CRUD_Template/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Articles</h1>
<a href="{% url 'articles:create' %}">[NEW]</a>
<hr>
{% for article in articles %}
  <p>글 번호 : {{ article.pk }}</p>
  <p>글 제목 : {{ article.title }}</p>
  <p>글 내용 : {{ article.content }}</p>
  <a href="{{ article.get_absolute_url }}">[DETAIL]</a>
  <hr>
{% endfor %}
{% endblock %}

03_django/CRUD_Template/articles/templates/articles/update.html
{% extends "base.html" %}


{% block content %}
  <h1 class="text-center">UPDATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
    <input type="submit" value="제출"> 
  </form>
  <a href="{{ article.get_absolute_url }}">[back]</a>


{% endblock  %}

03_django/CRUD_Template/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    {% block content %}
    {% endblock  %}
  </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

03_django/CRUD_Template/jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'jobs:past_life' %}" method='POST'>
  {% csrf_token %}
  <label for="name">당신의 전생은?</label>
  <input type="text" name="name" id="name">
  <input type="submit" value="제출">

  </form>
{% endblock  %}

03_django/CRUD_Template/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ person.name }} 님의 전생은 {{ person.past_job }}입니다.</h1>
<img src="{{ image }}" alt="gif_img">

<a href="{% url 'jobs:index' %}">다시하기</a>
{% endblock content %}